# Use like:

# name: Backport Assistant
# on:
#   pull_request_target:
#     types:
#       - closed
#       - labeled
# permissions: write-all
# jobs:
#   backport:
#     # using `main` as the ref will keep your workflow up-to-date
#     uses: hashicorp/vault-workflows-common/.github/workflows/backport.yaml@main
#     secrets:
#       VAULT_ECO_GITHUB_TOKEN: ${{ secrets.VAULT_ECO_GITHUB_TOKEN }}

name: Run backport assistant

on:
  workflow_call:
    secrets:
      VAULT_ECO_GITHUB_TOKEN:
        required: true
        description: 'Should be different than the default GITHUB_TOKEN so that this workflow can merge commits into the backport branch.'

jobs:
  backport:
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.4.3
    steps:
      - name: Configure git with a token that has sufficient privileges
        run: |
          git config --global url."https://${{ secrets.VAULT_ECO_GITHUB_TOKEN }}@github.com".insteadOf https://github.com
      - name: Backport changes to targeted release branch
        run: backport-assistant backport -merge-method=squash -gh-automerge
        env:
          BACKPORT_LABEL_REGEXP: "backport/vault-(?P<target>\\d+\\.\\d+\\.\\w+)"
          BACKPORT_TARGET_TEMPLATE: "release/vault-{{.target}}"
          BACKPORT_MERGE_COMMIT: true
          GITHUB_TOKEN: ${{ secrets.VAULT_ECO_GITHUB_TOKEN }}