# Use like:

# name: Backport Assistant
# on:
#   pull_request_target:
#     types:
#       - closed
#       - labeled
# permissions: write-all
# jobs:
#   backport:
#     # using `main` as the ref will keep your workflow up-to-date
#     uses: hashicorp/vault-workflows-common/.github/workflows/backport.yaml@main

name: Run backport assistant

on:
  workflow_call: {}

jobs:
  backport:
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.2.2
    steps:
      - name: Run Backport Assistant for release branches
        run: backport-assistant backport
        env:
          BACKPORT_LABEL_REGEXP: "backport/vault-(?P<target>\\d+\\.\\d+\\.\\w+)"
          BACKPORT_TARGET_TEMPLATE: "release/vault-{{.target}}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
