# use like:

# name: JIRA Sync
# on:
#   issues:
#     types: [opened, closed, deleted, reopened]
#   pull_request_target:
#     types: [opened, closed, reopened]
#   issue_comment: # Also triggers when commenting on a PR from the conversation view
#     types: [created]
# jobs:
#   sync:
#     # using `main` as the ref will keep your workflow up-to-date
#     uses: hashicorp/vault-workflows-common/.github/workflows/jira.yaml@main
#     # assuming you use Vault to get secrets
#     # if you use GitHub secrets, use secrets.XYZ instead of steps.secrets.outputs.XYZ
#     secrets:
#       JIRA_SYNC_BASE_URL: ${{ steps.secrets.outputs.JIRA_SYNC_BASE_URL }}
#       JIRA_SYNC_USER_EMAIL: ${{ steps.secrets.outputs.JIRA_SYNC_USER_EMAIL }}
#       JIRA_SYNC_API_TOKEN: ${{ steps.secrets.outputs.JIRA_SYNC_API_TOKEN }}
#     with:
#       teams-array: '["foundations-eco"]'

on:
  workflow_call:
    inputs:
      teams-array:
        required: true
        type: string
        description: 'JSON formatted array of teams to create issues with, e.g. ["ecosystem", "foundations"]. Must use double quotes for each element.'
    secrets:
      JIRA_SYNC_BASE_URL:
        required: true
      JIRA_SYNC_USER_EMAIL:
        required: true
      JIRA_SYNC_API_TOKEN:
        required: true

name: JIRA Sync

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Jira sync
    steps:
    - name: Login
      uses: atlassian/gajira-login@45fd029b9f1d6d8926c6f04175aa80c0e42c9026 # v3.0.1
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_SYNC_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_SYNC_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_SYNC_API_TOKEN }}
    - name: Preprocess
      if: github.event.action == 'opened' || github.event.action == 'created'
      id: preprocess
      run: |
        if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
          echo "type=PR" >> "$GITHUB_OUTPUT"
        else
          echo "type=ISS" >> "$GITHUB_OUTPUT"
        fi

        echo "==> Determining team labels"
        teams_field='[]'
        for team in $(echo '${{ inputs.teams-array }}' | jq -r '.[]'); do
          if [[ "$team" == "applications" ]] || [[ "$team" == "foundations" ]]; then
            t="${team}-eco"
            echo "==> Found deprecated team label \"$team\", overwriting with \"$t\""
            # append team label to array
            teams_field="$(echo "$teams_field" | jq --compact-output --arg tt "$t" '. |= . + [$tt]')"
          fi
        done

        if [[ $(echo "${teams_field}" | jq 'length') == 0 ]]; then
          echo "==> No deprecated fields were overwritten, let labels passthrough"
          teams_field='${{ inputs.teams-array }}'
        fi

        echo "==> Using labels: $teams_field"
        echo "teams_array=${teams_field}" >> "$GITHUB_OUTPUT"

    - name: Create ticket
      if: github.event.action == 'opened' && !(github.event.pull_request && contains(github.event.pull_request.labels.*.name, 'dependencies')) && (github.actor != 'dependabot[bot]')
      uses: tomhjp/gh-action-jira-create@3ed1789cad3521292e591a7cfa703215ec1348bf # v0.2.1
      with:
        project: VAULT
        issuetype: "GH Issue"
        summary: "${{ github.event.repository.name }} [${{ steps.preprocess.outputs.type }} #${{ github.event.issue.number || github.event.pull_request.number }}]: ${{ github.event.issue.title || github.event.pull_request.title }}"
        description: "${{ github.event.issue.body || github.event.pull_request.body }}\n\n_Created from GitHub Action for ${{ github.event.issue.html_url || github.event.pull_request.html_url }} from ${{ github.actor }}_"
        # customfield_10089 is Issue Link custom field
        # customfield_10091 is team custom field
        extraFields: '{"fixVersions": [{"name": "TBD"}], "customfield_10091": ${{ steps.preprocess.outputs.teams_array }}, "customfield_10089": "${{ github.event.issue.html_url || github.event.pull_request.html_url }}"}'
    - name: Search
      if: github.event.action != 'opened'
      id: search
      uses: tomhjp/gh-action-jira-search@04700b457f317c3e341ce90da5a3ff4ce058f2fa # v0.2.2
      with:
        # cf[10089] is Issue Link custom field
        jql: 'project = "VAULT" and cf[10089]="${{ github.event.issue.html_url || github.event.pull_request.html_url }}"'
    - name: Sync comment
      if: github.event.action == 'created' && steps.search.outputs.issue
      uses: tomhjp/gh-action-jira-comment@6eb6b9ead70221916b6badd118c24535ed220bd9 # v0.2.0
      with:
        issue: ${{ steps.search.outputs.issue }}
        comment: "${{ github.actor }} ${{ github.event.review.state || 'commented' }}:\n\n${{ github.event.comment.body || github.event.review.body }}\n\n${{ github.event.comment.html_url || github.event.review.html_url }}"
    - name: Close ticket
      if: (github.event.action == 'closed' || github.event.action == 'deleted') && steps.search.outputs.issue
      uses: atlassian/gajira-transition@38fc9cd61b03d6a53dd35fcccda172fe04b36de3 # v3
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: Closed
    - name: Reopen ticket
      if: github.event.action == 'reopened' && steps.search.outputs.issue
      uses: atlassian/gajira-transition@38fc9cd61b03d6a53dd35fcccda172fe04b36de3 # v3
      with:
        issue: ${{ steps.search.outputs.issue }}
        # transitions issue to 'Pending Triage' status
        transition: Reopen
