name: Tag Plugin

on:
  workflow_call:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    env:
      PLUGIN_NAME: ${GITHUB_REPOSITORY#*/}
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: './go.mod'

      - name: Build plugin
        run : |
          go build -o "$PLUGIN_NAME"


      - name: Scan
        uses: hashicorp/security-scanner@v0.0.2
        with:
          binary: "$PLUGIN_NAME"

      - name: Check security-scanner results
        run: |
          # ensure we have a "runs" key
          if jq -e 'has("runs")' results.sarif > /dev/null; then
            # ensure "runs" is non-empty and we have a "results" key
            if jq -e 'select(.runs != []).runs[] | has("results")' results.sarif > /dev/null; then
              # ensure "results" is non-empty
              if jq -e 'select(.runs != []).runs[] | select(.results != [])' results.sarif > /dev/null; then
                echo "::error::vulnerabilities found, please check logs"
                exit 1
              fi
            fi
          fi

      - name: Show security-scanner logs
        if: failure()
        run: |
          summary=$(jq -r '.runs[].results[].message.text' results.sarif | sort | uniq)
          echo "${summary}" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

  tag-plugin:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Cut tag
        run: |
          echo "::info::git tag"
          git tag
          echo "working dir:"
          pwd
