# use like:

# name: Run Tests
# on:
#   push:
# jobs:
#   run-tests:
#     # using `main` as the ref will keep your workflow up-to-date
#     uses: hashicorp/vault-workflows-common/.github/workflows/tests.yaml@main


name: Tests

on:
  workflow_call:
    inputs:
      build_tags:
        description: BUILD_TAGS to pass to the make targets
        required: false
        type: string
        default: ""
    secrets:
      gh_token:
        required: false
        description: GitHub token for accessing private repositories

permissions:
  contents: read

jobs:
  run-tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.gh_token }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: .go-version
      - name: Configure Git for private repos
        if: ${{ env.GH_TOKEN != '' }}
        run: |
          git config --global url."https://${{ env.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: Run Tests
        run: BUILD_TAGS=${{ inputs.build_tags }} make test

      - name: Run Test Build
        run: BUILD_TAGS=${{ inputs.build_tags }} make dev

