# use like:

# name: Run Tests
# on:
#   push:
# jobs:
#   run-tests:
#     # using `main` as the ref will keep your workflow up-to-date
#     uses: hashicorp/vault-workflows-common/.github/workflows/tests.yaml@main


name: Tests

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  run-tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: .go-version
      - name: Run Tests
        run: make test

      - name: Run Test Build
        run: make dev

