# use like:

# name: Run Tests
# on:
#   push:
# jobs:
#   run-tests:
#     # using `main` as the ref will keep your workflow up-to-date
#     uses: hashicorp/vault-workflows-common/.github/workflows/tests.yaml@main


name: Tests

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  get-go-version:
    name: "Determine Go toolchain version"
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Determine Go version
        id: get-go-version
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> "$GITHUB_OUTPUT"
  run-tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    needs:
      - get-go-version
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
          cache: true
      - name: Run Tests
        run: make test

      - name: Run Test Build
        run: make dev

